### ISSUE TITLE
[iOS] Enter ENS Name does not resolve names to addresses

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#566]
**Bug description**
In the latest app (release version), when adding  a safe using ENS name `alice.eth`, I get error "No resolver set for the record"

**Steps To Reproduce**
- Add safe
- Enter address using ENS name "alice.eth"

**Expected Result**
Safe with address  `0xcd2E72aEBe2A203b84f46DEEC948E6465dB51c75` is added

**Device & App version**
 - Device/OS: iPhone 6s, iOS 14
 - App version: 2.1.0 (3)
 
**Environment**
Production Mainnet

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Fixed in 2.2.0 (3)

**Comment by liliya-soroka** [comment]
The issue still exists:
2.2.0 (5) 
prod mainnet
os 13.7
There are some specific steps ( searching for them)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/782d626c-7f6e-4b4a-8961-262e6161716a)

@DmitryBespalov and @tschubotz , there is some situation when the issue still exists, but the priority can be changed to lower as it's not easy to get the error. I am searching for the steps

**Comment by liliya-soroka** [comment]
The issue was not reproduced in 2.3.0 -161

**Comment by liliya-soroka** [comment]
Reopened: 
The issue was reproduced:
Steps:
1. turn internet connectin off
2. call add safe
3. select enter ENS
4. enter ens name 
5. turn the internet connection on
6. reenter the last letter to activate ens name

Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bdd6c1e0-5f80-4fd3-87e9-4ddd6b4800cf)
Prod, mainnet
app version: 2.5.0(186)

**Comment by sche** [comment]
It should work

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (266)
